### ISSUE TITLE
can not find the output

### ISSUE THREAD

**Issue by phymasisic** [ChiChou/glskybox#1]
When I ran the code, I got:

E:\glskybox-master>python glskybox.py IMG_1501.jpg
[+] processing image: IMG_1501.jpg
Traceback (most recent call last):
  File "glskybox.py", line 20, in <module>
    [projector.run(source) for source in args.input]
  File "E:\glskybox-master\render.py", line 76, in run
    self.render(src)
  File "E:\glskybox-master\render.py", line 100, in render
    self.load_texture(filename)
  File "E:\glskybox-master\render.py", line 48, in load_texture
    buf = im.convert("RGB").tostring("raw", "RGB")
  File "D:\Python27\lib\site-packages\PIL\Image.py", line 686, in tostring
    "Please call tobytes() instead.")
Exception: tostring() has been removed. Please call tobytes() instead.

or

E:\glskybox-master>python glskybox.py westcampus.jpg
[+] processing image: westcampus.jpg
Traceback (most recent call last):
  File "glskybox.py", line 20, in <module>
    [projector.run(source) for source in args.input]
  File "E:\glskybox-master\render.py", line 76, in run
    self.render(src)
  File "E:\glskybox-master\render.py", line 100, in render
    self.load_texture(filename)
  File "E:\glskybox-master\render.py", line 48, in load_texture
    buf = im.convert("RGB").tostring("raw", "RGB")
  File "D:\Python27\lib\site-packages\PIL\Image.py", line 686, in tostring
    "Please call tobytes() instead.")
Exception: tostring() has been removed. Please call tobytes() instead.

But the folders "output\IMG_1501" and "output\westcampus" are empty. Why?

**Comment by ChiChou** [comment]
As pointed out in the Exception stack, this is due to a removed function in Pillow 3.0. 

The problem has been fixed in the latest commit. Please, update your code with `git pull`.
